# Use the official Python 3.11 image as a base
FROM python:3.11

# Install necessary packages
RUN apt-get update && apt-get install -y libgl1-mesa-glx

# Set the working directory in the container
WORKDIR /usr/app/src

# Copy the source code into the container
COPY ./src ./src

# Install Python dependencies
RUN pip install -r ./src/requirements.txt

# Set up the entrypoint script
RUN chmod +x ./src/entrypoint.sh

ENTRYPOINT ["./src/entrypoint.sh"]
