FROM python:3.11

RUN apt-get update && apt-get install -y libgl1-mesa-glx

# Set the working directory in the container
WORKDIR /usr/app/src

COPY ./src ./src

# Copy the YOLOv5 model file
RUN pip install -r ./src/requirements.txt

# Set up the entrypoint script

RUN chmod +x ./src/entry.sh

ENTRYPOINT ["./src/entry.sh"]

# ENTRYPOINT [ "python", "./src/detect.py" ]

# "--source", "--weights", "HumanModel.pt", "--save-txt", "--name", "ModelResults" ]


