version: '3'
services:
# pulled marc's camera docker. (not working. dont run)
  camera:
    container_name: camera_module
    image: <<fill in image name>>
    volumes:
      - raw:/usr/app/src/folder1
      - data:/usr/app/src/folder2
    command: ["--folder1", "/usr/app/src/folder1/", "--folder2", "/usr/app/src/folder2/", "/dev/video0"]


# put last since it deletes the image from raw volume
  shape_human:
    depends_on:
      - camera
    container_name: human_model
    image: shape_human-image
    volumes:
      -raw:/raw_images
    command: ["./src/entrypoint.sh"]

  color:
  # TODO: fix so it takes images like Jason's thing
    depends_on:
      - shape
    container_name: color_model
    image: color-image
    volumes:
      - raw:/usr/app/src/images
    command: ["/usr/app/src/images/"]
  
  alphanumeric:
    depends_on:
      - color # can change so that it also depends on shape but beware the consequences of that
    container_name: text_model
    image: alphanumeric-image
    volumes:
      - raw: /raw_images
    command: ["python", "/app/ocrModel.py"]


volumes:
  raw:
  data:
