version: '3'
services:
  camera:
    container_name: camera_module
    image: camera-image #NOT MADE YET
    volumes:
      - raw:/usr/app/src/folder1
      - data:/usr/app/src/folder2
    command: ["--folder1", "/usr/app/src/folder1/", "--folder2", "/usr/app/src/folder2/", "/dev/video0"]

# put last since it deletes the image from raw volume
  shape_human:
    build:
      - context: ./shape_human
      - dockerfile: Dockerfile
    depends_on:
      - camera
    container_name: human_model
    image: shape_human-image
    volumes:
      -raw:/raw_images
    command: ["./src/entrypoint.sh"]

  color:
    build:
      - context: ./color
      - dockerfile: Dockerfile
    depends_on:
      - shape_human
    container_name: color_model
    image: color-image
    volumes:
      - raw:/usr/app/src/images
    command: ["/usr/app/src/images/"]
  
  alphanumeric:
    build:
      - context: ./alphanumeric
      - dockerfile: Dockerfile
    depends_on:
      - color
    container_name: text_model
    image: alphanumeric-image
    volumes:
      - raw:/usr/app/src/images
    command: ["/usr/app/src/images/"]


volumes:
  raw:
  data:
