version: '3'
services:
  camera:
    container_name: camera_module
    image: joestrada1022/camera
    volumes:
      - raw:/usr/app/src/folder1
      - processing:/usr/app/src/folder2
    command: ["--folder1", "/usr/app/src/folder1/", "--folder2", "/usr/app/src/folder2/", "/dev/video0"]
    

  color:
    container_name: color_model
    image: joestrada1022/odlc_color_model
    volumes:
      - processing:/usr/app/src/images
    command: ["/usr/app/src/images/*"]

volumes:
  raw:
  processing:
